swagger: '3.0'
info:
  description:
  version: 0.0.1-SNAPSHOT
  title: Swagger Citizen API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost
basePath: /v1
tags:
  - name: citizen
    description: Everything about your Citizen
schemes:
  - http #security schemes
paths:
  '/citizen':
    get:
      tags:
      - citizen
      summary: List citizens
      description: Returns list of Citizen
      operationId: getAllCitizens
      produces:
      - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Citizen'
    post:
      tags:
      - citizen
      summary: Create citizen
      description: Creates a new Citizen
      operationId: createCitizen
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      requestBody:
#        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Citizen'
          application/xml:
            schema:
              $ref: '#/components/schemas/Citizen'
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Citizen'
        '400':
          description: Invalid input
  '/citizen/{citizenId}':
    get:
      tags:
        - citizen
      summary: Find citizen by ID
      description: Returns a single Citizen
      operationId: getCitizenDetails
      produces:
        - application/json
      parameters:
        - name: citizenId
          in: path
          description: ID of Citizen to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Citizen'
        '400':
          description: Invalid Citizen ID supplied
        '404':
          description: Citizen not found
    delete:
      tags:
      - citizen
      summary: Delete citizen by ID
      description: Deletes a single Citizen
      operationId: deleteCitizen
      parameters:
      - name: citizenId
        in: path
        description: ID of Citizen to delete
        required: true
        type: integer
        format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid Citizen ID supplied
        '404':
          description: Citizen not found
    put:
      tags:
      - citizen
      summary: Update citizen
      description: Updates an existing Citizen
      operationId: updateCitizen
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      parameters:
      - name: citizenId
        in: path
        description: ID of Citizen to update
        required: true
        type: integer
        format: int64
      requestBody:
        #        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Citizen'
          application/xml:
            schema:
              $ref: '#/components/schemas/Citizen'
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Citizen'
        '400':
          description: Invalid input
        '404':
          description: Citizen not found
definitions:
  Citizen:
    type: object
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
        description: Citizen First Name
      lastName:
        type: string
        description: Citizen Last Name
      birthday:
        type: string
        format: date
        description: Citizen Birthday
    xml:
      name: citizen
